### ISSUE TITLE
I am unable to install Tracer viewer V 3.0 

### ISSUE THREAD

**Issue by vamsivit** [pegasystems/pega-tracerviewer#4]

**Comment by vargm** [comment]
could you please describe it a bit more, what steps did you try in order to run.
You don't need to install anything here, it is a Java program, it can be run like any other java program, 'java -jar <jar file name>'. the "pega-tracerviewer-3.1.cmd" file supplied in the zip does the same , but it additionally set heap and GC related arguments.  To run, double click  or use Command Prompt to run the pega-tracerviewer-3.1.cmd file. Also Java 8 is a prerequisite for this tool to run.

**Comment by vamsivit** [comment]
Thanks for the info  vargm .

I think i had old version of Java. With new version it is working fine.

I appreciate your work in developing this.

Thanks,
Vamsi


Best Regards,
Vamsi Kakumani
571-342-1015
